### ISSUE TITLE
Subsurface render limit is broken

### ISSUE THREAD

**Issue by flaviozavan** [inclement/vivarium#104]
[The subsurface render limit logic](https://github.com/inclement/vivarium/commit/e7db49786b50650d8c77f1d1f7821021aeea10ef) fails for trees with a depth greater than 2. A real world consequence of this bug is that Firefox's permission dialogs don't get rendered (the ones were you allow webcam/location/etc access). I have [an experimental branch where the render limit code was removed (though some of the accompanying logic is still in place)](https://github.com/flaviozavan/vivarium/tree/unfocus-clear-workspace), Firefox works as expected there.

I am opening this issue to discuss if the render limit has a use I am unaware of, or rather, if we should fix it or remove it.

**Comment by flaviozavan** [comment]
I should have added that I am talking about [this line of code](https://github.com/inclement/vivarium/blob/4928b4807c8cc0a2db6182e27f5a819412524585/src/viv_render.c#L246), which only looks at the immediate children

**Comment by inclement** [comment]
I don't think the subsurface render limit is useful any more. I originally put it in as a hacky way to succeed in sort-of-correct surface rendering at a point where I didn't understand some of how subsurfaces were really supposed to work, but I'm pretty sure I eventually found the correct way and only left it in as I was using it for debugging at one point.

If getting rid of it appears useful then I'm definitely happy to do so.
