### ISSUE TITLE
xmodmap with inputs

### ISSUE THREAD

**Issue by mhdzli** [inclement/vivarium#108]
In Swaywm keyboard configuration for using multiple layouts or other custom keymap options is available with a  [custom keymap file](https://github.com/swaywm/sway/issues/4250) or using [`input { type:keyborad { <KEYBOARD_OPTIONS> }`](https://github.com/mhdzli/dotfiles/blob/5aec9de2377a62a7389942113553b2cc6a668afe/src/.config/sway/config#L402) in Swaywm config file.
Is there any implementation for this in `vivarium`

**Comment by inclement** [comment]
You can set the xkb config options via the config file [here](https://github.com/inclement/vivarium/blob/main/config/config.toml#L52). The syntax/options should match sway, as they're ultimately passed to libinput in the same way.

**Comment by mhdzli** [comment]
Thank you. Sorry my bad. Don't know how I missed that.

**Comment by mhdzli** [comment]
Sorry but is there any way to get the current keyboard layout in vivarium?

**Comment by inclement** [comment]
I don't think there is a way to get the current layout as it stands - Vivarium definitely doesn't specifically provide one, but I'm not sure if there's an independent way to query via any backend library.

What kind of thing are you wanting to do, it would help to think through how this could be added.
