### ISSUE TITLE
Segmentation fault, Hang up, Proper way to setup configuration.

### ISSUE THREAD

**Issue by ahmadraniri1994** [inclement/vivarium#11]
Compiled on my distro's (Arch + devuan) , successfully compiled but when I ran I got segmentation fault. Also , when I ran without configuration , it hung and I could not switch TTY . Also I still have no clue about the configuration, especially on "IPC" , do I need to "touch" the .txt file by my self or it's automatically created? Thanks.

**Comment by inclement** [comment]
I'm thinking there may be some bugs with how the configuration is loaded, and I'll look into that.

But, what's supposed to happen is Vivarium has a default config that is compiled in. If you create a ~/.config/vivarium/config.toml file it will use the settings you write there, but if you don't the default config should work fine. Segfaults are definitely not expected!

The IPC configuration is just a temporary hack to get waybar to update, it shouldn't be important or able to break anything. It probably has undue prominence in the README.

> Also , when I ran without configuration , it hung and I could not switch TTY

I think running without configuration is the best way to debug, as this should definitely work. Are you able to run within an existing X or wayland session and see what the terminal output is?

**Comment by inclement** [comment]
On testing, the default config has some idiosyncrasies specific to my system that may be causing crashes on others, I'll fix this.

**Comment by ahmadraniri1994** [comment]
Well, I'll look up into that, I'll give the update later, thanks.

**Comment by inclement** [comment]
I've just fixed the config loading at least enough that the defaults (with no config.toml) should hopefully work, and the CI is now successfully running Vivarium headless to catch regressions.

**Comment by ahmadraniri1994** [comment]
Well, Alhamdulillah, Thanks , it runs now, just need to set the "xkb" stuff properly, thanks again. Closed.

**Comment by inclement** [comment]
Glad to hear it. For what it's worth, I'm now fixing the settings loading to use good defaults where keys (like the xkb settings) are omitted.

**Comment by ahmadraniri1994** [comment]
Well, new issues appear, some keybinds not work though there is indicator that it's bonded to some action like "wofi --show run" (I have wofi installed). But some keybinds works too , like "quit' etc.

**Comment by ahmadraniri1994** [comment]
Okay, change it from do_exec to do_shell and "executable" to "command" make it work. Thanks.
