### ISSUE TITLE
[Question] device name to set tap-to-click on touchpad.

### ISSUE THREAD

**Issue by ahmadraniri1994** [inclement/vivarium#116]
Hello, does vivarium support tap-to-click ?
If does, how to configure it ?
I tried to enter my touchpad device name I got it from "libinput list-devices", but it doesn't work. Thanks

**Comment by inclement** [comment]
I think the "fingers" option for the `[[libinput]]` `click_method` in the config file does this, but I haven't tested it. I'll try to test later, I've been meaning to try to enable it on my laptop.

**Comment by ahmadraniri1994** [comment]
Thanks for replying, so where do we get `device-name` ? Is it from `sudo libinput list-devices` ?

**Comment by ahmadraniri1994** [comment]
I have these for libinput configuration and tap-to-click still doesn't work : 
```[[libinput-config]]
# Example libinput-config for a popular trackball:
device-name = "SynPS/2 Synaptics TouchPad"
scroll-method = "2-finger"
#scroll-button = 8
middle-emulation = true
left-handed = false
natural-scroll = true
disable-while-typing = false
click-method = "fingers"```

**Comment by inclement** [comment]
Yes, the device name from libinput list-devices should work. I'm not sure why it isn't working for you, it could be that the "fingers" method doesn't do what I thought or there could be a bug in Vivarium in setting this config. I'll try to test it on my own laptop at the weekend - it looks like I have exactly the same touchpad device name so hopefully I can make that work.

**Comment by ahmadraniri1994** [comment]
> I'll try to test it on my own laptop at the weekend

I'll wait, thanks.

**Comment by flaviozavan** [comment]
It looks like this feature can be toggled with [`libinput_device_config_tap_set_enabled`](https://wayland.freedesktop.org/libinput/doc/latest/api/group__config.html#ga3caf860883d4e2e42b7842599da03e56), which isn't called anywhere in the code. It should be almost trivial to introduce support for this, as well as for all the other options libinput supports

**Comment by ahmadraniri1994** [comment]
It's a bit out of topic, while waiting for the result, I made an attempt to show vivarium's workspaces on yambar bar, it's successful. You may check this : [Yambar for vivarium.](https://gist.github.com/lidgnulinux/0050d462e8b7a5f8ccd5a4b39f518658?fbclid=IwAR1thmrrEBe1fqB_hHack1QMPSO-2tMOEjlqNmZnedgVlaKj1yALLM8ltzM)

**Comment by inclement** [comment]
Thanks @flaviozavan, I somehow missed this important libinput option when I first set up the libinput code.

I've made PR #117 which adds the tap-to-click option, and tested that it works on my own trackpad, example config given on the PR. @ahmadraniri1994 would you be able to test that PR to double check I haven't missed something? No worries if that's a problem for you, I've tested that it works and seems good to merge.

**Comment by lidgnulinux** [comment]
@inclement Thanks, I'll try that.

**Comment by lidgnulinux** [comment]
Confirmed, tap to click is usable now, thanks @inclement .

**Comment by inclement** [comment]
Great, thanks @lidgnulinux for the report and for checking the fix.

Also delighted that Yambar works for displaying workspaces!

**Comment by ahmadraniri1994** [comment]
Wow, it works, thanks @inclement .
