### ISSUE TITLE
Autostarted waybar is not shown

### ISSUE THREAD

**Issue by ProjectInfinity** [inclement/vivarium#48]
Waybar launches but doesn't actually display on screen if I rely on vivarium to start it. 
If I launch waybar through a terminal it works fine.

Waybar v0.9.7

I am using default waybar section in the config.toml file:
```[bar]
command = "waybar"  # note this is a command to execute: this program must be installed to work
update-signal-number = 1```

**Comment by ProjectInfinity** [comment]
Sorry this can be ignored. Turns out that if I had another wayland compositor on TTY2 and Vivarium on TTY3. Things were not working as they should.

**Comment by inclement** [comment]
I've sometimes had a weird behaviour where waybar does start, but doesn't actually map a surface for several seconds (or even minutes) - it just appears suddenly after a while. I'll be interested to hear if you see that too.

Vivarium also should probably be able to tell waybar what WAYLAND_DISPLAY to use, I've opened #49 to track this although it probably won't get attention for a little while.
