### ISSUE TITLE
Janet as the configuration/scripting language

### ISSUE THREAD

**Issue by pepe** [inclement/vivarium#50]
Hello.

I am watching the Vivarium with great interest, I have yet not had time to start to use it myself, but I will definitely try on the secondary machine soon.

Anyway, as I was reading through the FAQ and some issues, I have found that you mean to create Vivarium, that it could be used as a library or be embedded. For this purpose, I think the Janet programming language http://janet-lang.org/ would be a great fit. It is a modern Lisp-like language with a good standard library and an excellent story using the C language.

Please do not take this as any pressure, but the head up. If you like to hear/read more, please ping me.

Have a nice day, and keep up the good work.

**Comment by inclement** [comment]
Thanks for the suggestion, I wasn't familiar with janet.

The key step in supporting this would really be having a clear api for starting Vivarium while passing in a C config including event bindings. Then, if that config was designed well, it should allow any language to wrap it easily. It's all blue sky thinking for now, making Vivarium feature-complete and robust is a bigger priority, but if it eventually works it should be very compatible with configuration from janet.

I'll close this issue as not active for now, but I'll try to mention it here again as and when I get to thinking about apis.

**Comment by pepe** [comment]
Thank you very much for taking Janet into consideration.

The best thing for me I guess is to start using Vivarium myself and see if the presumption makes any sense.
