### ISSUE TITLE
Vivarium doesn't correctly handle xdg-shell fullscreen state

### ISSUE THREAD

**Issue by inclement** [inclement/vivarium#85]
The xdg-shell protocol makes some specific demands of compositors when an xdg-shell surface is fullscreen:

> If the surface doesn't cover the whole output, the compositor will position the surface in the center of the output and compensate with with border fill covering the rest of the output. The content of the border fill is undefined, but should be assumed to be in some way that attempts to blend into the surrounding area (e.g. solid black).

Vivarium doesn't actually do this, but it does currently tell views they are fullscreen if they ask for it. This is a workaround mainly for firefox, as that freezes if a fullscreen request is denied unless the `full-screen-api.ignore-widgets` key is set to true in about:config.

I think we can support a proper fullscreen mode since xdg-shell is quite specific about how it should work (it isn't like a normal layout), but it needs a little thought.

I'd quite like to just not do what xdg-shell says is required, I don't see why the fullscreen state should be so restrictive, but that would be a straight protocol breach so best avoided.

**Comment by DriNeo** [comment]
Thank you for the info about the Firefox config !

**Comment by inclement** [comment]
Fixed by #106, which is enabled by default so firefox won't get into a broken state any more.
